### ISSUE TITLE
All (including required) GraphQL fields are optional when using inline fragments

### ISSUE THREAD

**Issue by sorenhoyer** [relay-tools/relay-compiler-language-typescript#193]
```
fragment MyComponent_foo on Foo {
  ... on Bar {
    id
  }
}
```

Even if Bar has id set as required in the GraphQL schema, all props, including these GQL required fields, will be optional in the generated interface.

**Comment by maraisr** [comment]
Can you please post the schema here also; or maybe a reproduction repo we can investigate? A fragment on its own doesn't generate types, but couple it with a schema it will. Im thinking there is something in your schema that isnt marked as required. Something like a `foo: Foo` instead of `foo: Foo!`.

**Comment by kastermester** [comment]
This is expected behavior - as when the returned type is not of type Bar (but some other Foo) you only get an empty object back.

**Comment by sorenhoyer** [comment]
@kastermester thanks for the answer. I still find it a bit awkward when required fields from the graphql schema is suddenly all turned into optional props in the generated types and you have to have undefined checks for each of the "required" fields in your components.

But if this is the intended behavior, thanks for clarifying.

**Comment by sibelius** [comment]
why not a fragment on `Bar`?
