### ISSUE TITLE
Cannot read property 'createKeywordTypeNode' of undefined

### ISSUE THREAD

**Issue by jagadeesh93** [relay-tools/relay-compiler-language-typescript#272]
I am getting this error on my application which uses relay-compiler-language-typescript it is currently hosted on AWS

The funny part is that it was working fine before 2 days ,and working fine on my local machine as well , 
But during the codebuild on aws it is failing . I haven't done any modifications to the graphql part for the past few months. 

I am using NodeJs 12 . and TypeScript Version ^3.8.3 Please comment if you guys need any further config details to troubleshoot it . @n1ru4l 
![image](https://user-images.githubusercontent.com/37651463/107876775-15f0e700-6ed9-11eb-9ce0-bc47c3666055.png)

**Comment by n1ru4l** [comment]
Oh, this could be because I removed deprecation typescript API usages. I guess we should revert that, release a new patch version and then do a major version bump which only supports typescript 4? What do you think @sibelius @alloy?

https://github.com/relay-tools/relay-compiler-language-typescript/blob/b186ac3d9d9682949638211c3126c015f8706b0f/package.json#L104-L112

@jagadeesh93 In the meantime you could pin down the previous version. or upgrade your project to typescript 4. Sorry for the inconvenience, I wasn't aware of the fact that this project still supported pre typescript 4.

**Comment by sibelius** [comment]
Can we make a major bump to support only ts 4?

**Comment by jagadeesh93** [comment]
@n1ru4l . Thank you . I have pinned to exact version `13.0.1` now its working fine . In my `package.json` file i mentioned as `^13.0.1` . Since you released the change to the minor version it breaks my application.
I think its better to include these type of changes in a major version bump. @sibelius   So it will ensure the backward compatibility of the code

**Comment by n1ru4l** [comment]
@jagadeesh93 This should be fixed in v13.0.5.

**Comment by alloy** [comment]
I'm good with releasing a new major version 👍

**Comment by n1ru4l** [comment]
CLosing this as it should be resolved.

**Comment by Yiyue15** [comment]
Hi, I've got this issue again... I saw that latest code requires `"typescript": ">=4.2.3"` is it ok if we could remove that?
