### ISSUE TITLE
Use in TS-package with module: commonjs

### ISSUE THREAD

**Issue by arieldf** [relay-tools/relay-compiler-language-typescript#42]
@alloy I have been fiddling around for several hours as I need to incorporate Relay in a module that is currently compiled with TS to a commonjs-module.

The result is that then the babel-relay-transform does not work. Changing to es2015 module fixes that part but breaks the interaction with other modules. I changed my babelrc to apply "transform-es2015-modules-commonjs" after the relay-transform, but that does not fix the issue.

Do you have any experience with this issue? I know this is not an issue directly related to this library, but I was thinking it was worth asking as I would assume it could also be an issue other people with experience. Feel free to just close this issue if it does not belong here.

**Comment by alloy** [comment]
Yup, see #40.

While it’s indeed not an issue with this project; if you can share details (logs etc) about _how_ it “breaks the interaction with other modules” and how adding the transform did not fix the issue (and details on what even that issue is), then I can see if there’s any help I can offer.

**Comment by arieldf** [comment]
I solved this one by moving the Relay-part to a separate npm-package. I am fine with this solution
