### ISSUE TITLE
Input Types generated as readonly

### ISSUE THREAD

**Issue by TassiloSinghammerVolue** [relay-tools/relay-compiler-language-typescript#580]
Is it on purpose that with Relay 13 arrays in input types are now being generated as ReadonlyArray?
That's kind of cumbersome, as one especially wants to modify inputs like adding/removing filters etc.

**Comment by saihaj** [comment]
You don't need to use this package anymore for generating types with relay 13. Since it generates TS types for you.
![image](https://user-images.githubusercontent.com/44710980/149640899-cdf9bf85-6870-40e4-a7ce-dbe667af6acd.png)

https://github.com/facebook/relay/releases/tag/v13.0.0

You should file issue in the Relay repo.
